// Code generated by mockery v2.43.2. DO NOT EDIT.

package grpcServer

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// mockGrpcServerer is an autogenerated mock type for the grpcServerer type
type mockGrpcServerer struct {
	mock.Mock
}

// GracefulStop provides a mock function with given fields:
func (_m *mockGrpcServerer) GracefulStop() {
	_m.Called()
}

// Serve provides a mock function with given fields: lis
func (_m *mockGrpcServerer) Serve(lis net.Listener) error {
	ret := _m.Called(lis)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(net.Listener) error); ok {
		r0 = rf(lis)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *mockGrpcServerer) Stop() {
	_m.Called()
}

// newMockGrpcServerer creates a new instance of mockGrpcServerer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGrpcServerer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGrpcServerer {
	mock := &mockGrpcServerer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
