// Code generated by mockery v2.43.2. DO NOT EDIT.

package sharedTypes

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLogPublisher is an autogenerated mock type for the LogPublisher type
type MockLogPublisher struct {
	mock.Mock
}

// Error provides a mock function with given fields: msg, args
func (_m *MockLogPublisher) Error(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// ErrorContext provides a mock function with given fields: ctx, msg, args
func (_m *MockLogPublisher) ErrorContext(ctx context.Context, msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: msg, args
func (_m *MockLogPublisher) Info(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// InfoContext provides a mock function with given fields: ctx, msg, args
func (_m *MockLogPublisher) InfoContext(ctx context.Context, msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: msg, args
func (_m *MockLogPublisher) Warn(msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WarnContext provides a mock function with given fields: ctx, msg, args
func (_m *MockLogPublisher) WarnContext(ctx context.Context, msg string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewMockLogPublisher creates a new instance of MockLogPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogPublisher {
	mock := &MockLogPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
